name: CI

on: 
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
        
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint $(git ls-files '*.py')
        
    - name: Run UnitTests
      run: |
        python tests.py
        

    - name: Deploy to Heroku Dev
      # You may pin to the exact commit or the version.
      # uses: mtsmachado8/heroku-deploy@5bf18e5f6160beaccc01c678d0aaa81963434e74
      uses: mtsmachado8/heroku-deploy@v2.0.3
      with:
        # Email Linked to your Heroku Account
        email: ${{ secrets.HEROKU_EMAIL }}
        # Your Heroku API Key
        api_key: ${{ secrets.HEROKU_API_KEY}}
        # Your Heroku App Name
        app_name: ${{ secrets.HEROKU_APP_NAME }}
